### ISSUE TITLE
登录失败麻烦问问是哪里设置不对

### ISSUE THREAD

**Issue by apple524** [cream-sec/NSD-GUI#1]
防火墙是华为的USG6330
管理员这里 设置了apiadmin 的用户
北向接口配置也打开了RESTCONF
![image](https://github.com/user-attachments/assets/168a3b12-21a6-47ec-b07f-5e29373ceeab)
麻烦问问为啥软件提示连接失败，谢谢

**Comment by cream-sec** [comment]
嗯嗯 你设置北向服务端口为9000即可（程序里写死了），账号和密码你自定义就行。后续我再更新程序把端口加上去！
